Repository shenxiangzhuang/beer, pull requests merged in 2024-08, with the labels that each got.

#62 Fix: 7_curing_compulsive_gambler hidden solution1
  docs/fifty/7_curing_compulsive_gambler.md
Labels: documentation

#63 release: 0.1.0
  .gitignore
  poetry.lock
  pyproject.toml
Labels: release

#66 docs(readme): add wechat qr codes
  README.md
  asset/qr_code/ds_group.png
  asset/qr_code/mathew.png
Labels: documentation

#67 docs(readme): qr code link
  README.md
Labels: documentation

#70 Solution: [0, 1]均匀取点，单调序列的期望长度
  docs/misc/1_expectation_of_length_of_maximum_monotone_sequence.md
  mkdocs.yml
Labels: problem, solution

#71 Solution2: [0, 1]均匀取点，单调序列的期望长度
  docs/misc/1_expectation_of_length_of_maximum_monotone_sequence.md
Labels: problem, solution

#73 Deps/change to uv
  .github/workflows/build_docs.yml
  poetry.lock
  pyproject.toml
  uv.lock
Labels: enhancement

#76 add: comment system
  overrides/partials/comments.html
Labels: enhancement

#78 fix(misc_01): unify notation usage
  docs/misc/1_expectation_of_length_of_maximum_monotone_sequence.md
Labels: enhancement

#79 Solution3(Simulation): [0, 1]均匀取点，单调序列的期望长度
  docs/misc/1_expectation_of_length_of_maximum_monotone_sequence.md
  docs/misc/snippet/1_monotone_sequence.py
Labels: problem, solution

#81 add: issue templates
  .github/ISSUE_TEMPLATE/problem_solution_error.md
  .github/ISSUE_TEMPLATE/problem_suggestion.md
Labels: enhancement

#82 add: pr template
  .github/pull_request_template.md
Labels: enhancement

#83 add: contributing & code of conduct
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#84 add: security policy
  SECURITY.md
Labels: enhancement

#86 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#89 Docs/fix link
  README.md
Labels: documentation
